### ISSUE TITLE
Support for extaernal applications cnd-based replays (plain deployer)

### ISSUE THREAD

**Issue by planthaber** [dfki-ric/xrock_gui_model#15]
It would be great if the gui could support setting up this generic applications (binary).

Recently the cnd-model got support for launching playbacks of logfiles, apart from just launching the replay application, there are additional task models needed, the definition looks like this:

The tasks in the description below don't have a deployment as they are simulated by the logfile playback.

```yaml
connections:

deployments:
  replay:
    deployer: plain              # Use 'plain' deployment
    hostID: localhost
    process_name: rock-replay2   # rock-replay2 has to be specified as process_name
    cmdLineArgs:
#      - "--headless"            # when set, no playback GUI will be started, but playback will be started automatically
      - "--no-exit"              # To prevent rock-replay2 to exit after log playback finished. Exit would cause an inconsistent CND state
      - "--quiet"                # Prevent rock-replay2 to print many command line printouts resulting in large text log files
      - "/path/to/my/logfile/artemis_area_exploration_Logger.0.log"
      - "/path/to/another/logfile/artemis_navigation_Logger.0.log" # Multiuple logfiles can be loaded in one deployment
    taskList:
      area_exploration: area_exploration   # All tasks that are used in the CND have to be listed here as well
      motion_controller: motion_controller
tasks:
  area_exploration:
    activity:
      realtime: false
      type: TRIGGERED
    priority: 0
    state: RUNNING
    type: area_exploration::Task
  motion_controller:
    activity:
      period: 0.01
      priority: 82
      realtime: true
      type: PERIODIC
    priority: 0
    state: RUNNING
    type: motion_controller::Task

connections: {}   # Connections to live oroGen tasks are possible. But connections from live tasks to log files tasks obviosly not
```
